// Auto-generated by train/train_sheila.py -- do not edit.
// sheila, H=4 WL=1, AUC 93.7%, nphase=2 shift=1 centre=6 nframe=8
// hidden template 149/192 non-zero (78%); zeros drop out of the adder tree.
localparam [383:0] WW_ROW      = 384'h3c00c515514115514555157f7d57d5715355c57c40d731ff15315d15fd5fd7fc7fdff0ff54d5cd4dc4dc4d1715315f15;
localparam [23:0] WW_HBIAS    = 24'hf3f07f;
localparam [7:0] WW_W2       = 8'hdd;
localparam [9:0] WW_THRESH_PK = 10'h0c;
// hidden bias (decimal): [-1, 1, -1, -4]
// output weights: [1, -1, 1, -1]   threshold: 12
