// Auto-generated by train/train_sheila.py -- do not edit.
// dogbark, H=4 WL=1, AUC 79.7%, nphase=2 shift=1 centre=4 nframe=8
// hidden template 165/192 non-zero (86%); zeros drop out of the adder tree.
localparam [383:0] WW_ROW      = 384'hffff3ff7f35f35f7df7df55c57fdcf3cffcffcf14f54f55fff34c7557557177373fdc7dd3f1ff5ff54c7577547077ff4;
localparam [23:0] WW_HBIAS    = 24'hfce038;
localparam [7:0] WW_W2       = 8'hd5;
localparam [9:0] WW_THRESH_PK = 10'h006;
// hidden bias (decimal): [-8, 0, 14, -1]
// output weights: [1, 1, 1, -1]   threshold: 6  (validation clip FPR 5%, set by eval_header.py --set-fpr)
