// Auto-generated by train/train_sheila.py -- do not edit.
// water, H=4 WL=1, AUC 68.9%, nphase=2 shift=1 centre=6 nframe=8
// hidden template 150/192 non-zero (78%); zeros drop out of the adder tree.
localparam [383:0] WW_ROW      = 384'h55f55f15f15f15315f15f15f075170304477747007037375d5fd5fd53d5f15715715f153c45134137f45537f75d75d74;
localparam [23:0] WW_HBIAS    = 24'h13f03b;
localparam [7:0] WW_W2       = 8'hcd;
localparam [9:0] WW_THRESH_PK = 10'h003;
// hidden bias (decimal): [-5, 0, -1, 4]
// output weights: [1, -1, 0, -1]   threshold: 3  (validation clip FPR 5%, set by eval_header.py --set-fpr)
