// Auto-generated by train/train_sheila.py -- do not edit.
// siren, H=4 WL=1, AUC 81.0%, nphase=2 shift=1 centre=4 nframe=8
// hidden template 157/192 non-zero (82%); zeros drop out of the adder tree.
localparam [383:0] WW_ROW      = 384'h4d17153117157157117ddfddffdffd7fd3fd5dd4dd5dd55d0dc0ddddc15ffdffcd3cffdf05fd43d5fd73d43373073d47;
localparam [23:0] WW_HBIAS    = 24'hec6fc4;
localparam [7:0] WW_W2       = 8'hfd;
localparam [9:0] WW_THRESH_PK = 10'h000;
// hidden bias (decimal): [4, -1, 6, -5]
// output weights: [1, -1, -1, -1]   threshold: 0  (validation clip FPR 5%, set by eval_header.py --set-fpr)
