// Auto-generated by train/train_sheila.py -- do not edit.
// catmeow, H=4 WL=1, AUC 79.7%, nphase=2 shift=1 centre=6 nframe=8
// hidden template 151/192 non-zero (79%); zeros drop out of the adder tree.
localparam [383:0] WW_ROW      = 384'h133d13dc31df1571d711711353f17333f47f5f1775735335143dd3dd3dd3d571d7d571df05dd71f51f71f51c5cd57d5f;
localparam [23:0] WW_HBIAS    = 24'h04003f;
localparam [7:0] WW_W2       = 8'hdd;
localparam [9:0] WW_THRESH_PK = 10'h007;
// hidden bias (decimal): [-1, 0, 0, 1]
// output weights: [1, -1, 1, -1]   threshold: 7  (validation clip FPR 5%, set by eval_header.py --set-fpr)
