// Auto-generated by train/train_sheila.py -- do not edit.
// siren, H=4 WL=1, AUC 76.2%, nphase=2 shift=1 centre=6 nframe=8
// hidden template 156/192 non-zero (81%); zeros drop out of the adder tree.
localparam [383:0] WW_ROW      = 384'h7334f35477c77c53553d5f5535ff7ff7f37f47f05f73f47f753757371fd4f553037f377fd70d70d7cd3cd7dd7cd3317d;
localparam [23:0] WW_HBIAS    = 24'h00903b;
localparam [7:0] WW_W2       = 8'hfd;
localparam [9:0] WW_THRESH_PK = 10'h000;
// hidden bias (decimal): [-5, 0, 9, 0]
// output weights: [1, -1, -1, -1]   threshold: 0  (validation clip FPR 5%, set by eval_header.py --set-fpr)
