// Auto-generated by train/train_sheila.py -- do not edit.
// babycry, H=4 WL=1, AUC 72.4%, nphase=2 shift=1 centre=6 nframe=8
// hidden template 140/192 non-zero (73%); zeros drop out of the adder tree.
localparam [383:0] WW_ROW      = 384'hdf31d31f31d7117117d171171f31c30c70d71d75d75d75d71dfd03dffd13d53d13157d13d41141171171131d71c75c71;
localparam [23:0] WW_HBIAS    = 24'h00703c;
localparam [7:0] WW_W2       = 8'hfd;
localparam [9:0] WW_THRESH_PK = 10'h005;
// hidden bias (decimal): [-4, 0, 7, 0]
// output weights: [1, -1, -1, -1]   threshold: 5  (validation clip FPR 5%, set by eval_header.py --set-fpr)
