// Auto-generated by train/train_sheila.py -- do not edit.
// dogbark, H=4 WL=1, AUC 75.7%, nphase=2 shift=1 centre=6 nframe=8
// hidden template 152/192 non-zero (79%); zeros drop out of the adder tree.
localparam [383:0] WW_ROW      = 384'hd5415315715313fd1fd7fd53043347f45d4157d54d13d3f3515155514cd77d77d73557f045315f353ff5ff5d3517157d;
localparam [23:0] WW_HBIAS    = 24'h0bf0ff;
localparam [7:0] WW_W2       = 8'hdd;
localparam [9:0] WW_THRESH_PK = 10'h004;
// hidden bias (decimal): [-1, 3, -1, 2]
// output weights: [1, -1, 1, -1]   threshold: 4  (validation clip FPR 5%, set by eval_header.py --set-fpr)
