// Auto-generated by train/train_sheila.py -- do not edit.
// babycry, H=4 WL=1, AUC 78.5%, nphase=2 shift=1 centre=4 nframe=8
// hidden template 149/192 non-zero (78%); zeros drop out of the adder tree.
localparam [383:0] WW_ROW      = 384'h0f54f53f10f51c50fd54d54d143d77c773770373f73d75c7fccffdffdfcc3fd4fd5fd55cf17153543d47d47074c571d7;
localparam [23:0] WW_HBIAS    = 24'h083040;
localparam [7:0] WW_W2       = 8'hdd;
localparam [9:0] WW_THRESH_PK = 10'h004;
// hidden bias (decimal): [0, 1, 3, 2]
// output weights: [1, -1, 1, -1]   threshold: 4  (validation clip FPR 5%, set by eval_header.py --set-fpr)
