// Auto-generated by train/train_sheila.py -- do not edit.
// vad, H=4 WL=1, AUC 67.0%, nphase=2 shift=1 centre=4 nframe=8
// hidden template 153/192 non-zero (80%); zeros drop out of the adder tree.
localparam [383:0] WW_ROW      = 384'h05d3fd71d7dd3fdc7f47dc7fff5fc41031535435437c5fd5c7d05dfddfddf1145155d555f75147543577034fc5fc55f1;
localparam [23:0] WW_HBIAS    = 24'h1bdff9;
localparam [7:0] WW_W2       = 8'hdd;
localparam [9:0] WW_THRESH_PK = 10'h005;
// hidden bias (decimal): [-7, -1, -3, 6]
// output weights: [1, -1, 1, -1]   threshold: 5  (validation clip FPR 5%, set by eval_header.py --set-fpr)
