// Auto-generated by train/train_sheila.py -- do not edit.
// clap, H=4 WL=1, AUC 72.3%, nphase=2 shift=1 centre=6 nframe=8
// hidden template 160/192 non-zero (83%); zeros drop out of the adder tree.
localparam [383:0] WW_ROW      = 384'hd5fdd3d5fd57d5fd5fd5fddf5d301f017533ff4ff3037155d50dd3d5fd5fd5fd1fdcf10fd77d47d743f7077c75d75d44;
localparam [23:0] WW_HBIAS    = 24'hfff0bf;
localparam [7:0] WW_W2       = 8'hdd;
localparam [9:0] WW_THRESH_PK = 10'h005;
// hidden bias (decimal): [-1, 2, -1, -1]
// output weights: [1, -1, 1, -1]   threshold: 5  (validation clip FPR 5%, set by eval_header.py --set-fpr)
