// Auto-generated by train/train_sheila.py -- do not edit.
// mosquito, H=4 WL=1, AUC 63.0%, nphase=2 shift=1 centre=6 nframe=8
// hidden template 161/192 non-zero (84%); zeros drop out of the adder tree.
localparam [383:0] WW_ROW      = 384'h15c35d35c05df7f553f0f15f1ff5ff5ff57f57f13fc7ffff4355f103d5355103f5514ff53fc3ffffffffffffffffffff;
localparam [23:0] WW_HBIAS    = 24'hf8b03a;
localparam [7:0] WW_W2       = 8'h75;
localparam [9:0] WW_THRESH_PK = 10'h007;
// hidden bias (decimal): [-6, 0, 11, -2]
// output weights: [1, 1, -1, 1]   threshold: 7  (validation clip FPR 5%, set by eval_header.py --set-fpr)
