// Auto-generated by train/train_sheila.py -- do not edit.
// vad, H=4 WL=1, AUC 63.7%, nphase=2 shift=1 centre=6 nframe=8
// hidden template 151/192 non-zero (79%); zeros drop out of the adder tree.
localparam [383:0] WW_ROW      = 384'hdf3dd7df7cf7d57d57154154071f01ff1d4c55f55f553fd5cff1ff0df3df01ffffcffcfff3117d54f54f13ff01f0134d;
localparam [23:0] WW_HBIAS    = 24'h0bf0c0;
localparam [7:0] WW_W2       = 8'hdd;
localparam [9:0] WW_THRESH_PK = 10'h003;
// hidden bias (decimal): [0, 3, -1, 2]
// output weights: [1, -1, 1, -1]   threshold: 3  (validation clip FPR 5%, set by eval_header.py --set-fpr)
