"""Evaluate an exported weight set and emit host-side artifacts.

    python train/export.py --tag w4_h16
    python train/export.py --tag w4_h16 --image 0 --stream

Produces, under artifacts/:
    weights_<tag>.h        packed int4 weights + biases for an MCU host
    stream_<tag>_img<N>.bin  ready-to-play byte stream: 2 bytes per beat,
                             [data_byte, is_cmd] -- feed byte to ui_in and
                             is_cmd to uio_in[1] with uio_in[0]=1.
"""

from __future__ import annotations

import argparse
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import hw  # noqa: E402


def full_test_accuracy(m) -> tuple[float, np.ndarray]:
    (_, _), (xte, yte) = hw.load_mnist_u4(hw.DEFAULT_DATA_DIR)
    pred, _, _ = hw.infer_int_batch(m["w1"], m["b1"], m["w2"], m["b2"], m["shift1"], xte)
    cm = np.zeros((10, 10), dtype=int)
    for t, p in zip(yte, pred):
        cm[t, p] += 1
    return float((pred == yte).mean()), cm


def check_stream(m, n_images: int = 10) -> int:
    """Replay the host protocol through the FSM spec and compare to infer_int."""
    (_, _), (xte, _) = hw.load_mnist_u4(hw.DEFAULT_DATA_DIR)
    for i in range(n_images):
        st = hw.build_stream(m["w1"], m["b1"], m["w2"], m["b2"], m["shift1"], xte[i])
        sm = hw.StreamModel(m["hidden"]).run(st)
        ref, hid, _ = hw.infer_int(m["w1"], m["b1"], m["w2"], m["b2"], m["shift1"], xte[i])
        assert sm.result_valid, f"image {i}: FINISH never asserted"
        assert not sm.acc_ovf, f"image {i}: accumulator overflow"
        assert sm.hidden == hid.tolist(), f"image {i}: hidden mismatch"
        assert sm.best_class == ref, f"image {i}: class {sm.best_class} != {ref}"
    return n_images


def write_c_header(m, path: str):
    H, N, C = m["hidden"], hw.N_IN, hw.N_CLASS

    def nibbles(arr):
        """Pack a row of int4 weights two per byte, low nibble first."""
        flat = [int(v) & 0xF for v in np.asarray(arr).reshape(-1)]
        if len(flat) % 2:
            flat.append(0)
        return [flat[i] | (flat[i + 1] << 4) for i in range(0, len(flat), 2)]

    def carr(name, vals, per_line=16):
        body = ""
        for i in range(0, len(vals), per_line):
            body += "    " + ", ".join(f"{v:>6}" for v in vals[i:i + per_line]) + ",\n"
        return f"static const int32_t {name}[{len(vals)}] = {{\n{body}}};\n\n"

    with open(path, "w") as f:
        f.write("/* Auto-generated by train/export.py -- do not edit. */\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(f"#define MNIST_HIDDEN   {H}\n")
        f.write(f"#define MNIST_INPUTS   {N}\n")
        f.write(f"#define MNIST_CLASSES  {C}\n")
        f.write(f"#define MNIST_SHIFT1   {m['shift1']}\n")
        f.write(f"#define MNIST_ACC_W    {hw.ACC_W}\n")
        f.write(f"#define MNIST_STREAM_BYTES {hw.stream_length(H, N, C)}\n\n")
        f.write("/* w1 packed two int4 weights per byte, row-major (H x 784). */\n")
        f.write("static const uint8_t mnist_w1_packed[%d] = {\n" % (H * N // 2))
        pk = nibbles(m["w1"])
        for i in range(0, len(pk), 16):
            f.write("    " + ", ".join(f"0x{v:02x}" for v in pk[i:i + 16]) + ",\n")
        f.write("};\n\n")
        f.write("/* w2 packed the same way (10 x H). */\n")
        pk2 = nibbles(m["w2"])
        f.write("static const uint8_t mnist_w2_packed[%d] = {\n" % len(pk2))
        for i in range(0, len(pk2), 16):
            f.write("    " + ", ".join(f"0x{v:02x}" for v in pk2[i:i + 16]) + ",\n")
        f.write("};\n\n")
        f.write(carr("mnist_b1", [int(v) for v in m["b1"]]))
        f.write(carr("mnist_b2", [int(v) for v in m["b2"]]))


def write_stream_bin(m, index: int, path: str) -> int:
    (_, _), (xte, yte) = hw.load_mnist_u4(hw.DEFAULT_DATA_DIR)
    st = hw.build_stream(m["w1"], m["b1"], m["w2"], m["b2"], m["shift1"], xte[index])
    with open(path, "wb") as f:
        f.write(bytes(b for beat in st for b in beat))
    return int(yte[index])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tag", default="w4_h16")
    ap.add_argument("--image", type=int, default=0)
    ap.add_argument("--stream", action="store_true", help="also dump a byte stream")
    ap.add_argument("--check", type=int, default=10, help="images to replay through the FSM spec")
    args = ap.parse_args()

    m = hw.load_weights(args.tag)
    H = m["hidden"]
    print(f"tag={args.tag} mode={m['mode']} hidden={H} shift1={m['shift1']} "
          f"acc_w={hw.ACC_W}")

    acc, cm = full_test_accuracy(m)
    print(f"integer test accuracy (10 000 images): {acc*100:.2f}%")
    print("confusion matrix (rows = truth):")
    for i, row in enumerate(cm):
        print(f"  {i}: " + " ".join(f"{v:4d}" for v in row))

    n = check_stream(m, args.check)
    print(f"host protocol replay: {n} images, StreamModel == infer_int")

    nz1 = int((m["w1"] != 0).sum())
    print(f"w1 nonzero {nz1}/{m['w1'].size} ({100*nz1/m['w1'].size:.1f}%), "
          f"|b1| max {int(np.abs(m['b1']).max())}, |b2| max {int(np.abs(m['b2']).max())}")
    print(f"stream length: {hw.stream_length(H)} bytes "
          f"= {hw.stream_length(H)*20/1000:.0f} us/image at 50 MHz "
          f"({50e6/hw.stream_length(H):.0f} images/s)")

    hdr = os.path.join(hw.ARTIFACT_DIR, f"weights_{args.tag}.h")
    write_c_header(m, hdr)
    print(f"wrote {os.path.relpath(hdr)}")

    if args.stream:
        p = os.path.join(hw.ARTIFACT_DIR, f"stream_{args.tag}_img{args.image}.bin")
        label = write_stream_bin(m, args.image, p)
        print(f"wrote {os.path.relpath(p)} (image {args.image}, label {label})")


if __name__ == "__main__":
    main()
