"""Emit src/kws_weights.svh and the cocotb test vectors from a trained model.

    python3 train/kws_export.py --tag default
    python3 train/kws_export.py --placeholder 5,4,12,4    # untrained header

The header is the *only* thing that carries trained parameters into silicon --
there is no weight-loading interface on the tile -- so this script also proves
the constants it writes cannot break the RTL's arithmetic:

  * every weight is inside the int4 range the 4-bit ROM slice can hold;
  * the worst-case running |partial sum| stays inside SCORE_W, which is what
    lets the RTL accumulate step by step while the golden model saturates only
    at the end and still agree bit for bit;
  * the filterbank microcode written here comes from `kws_hw.bank_table`, so
    the gates and the model cannot be tuned to different corner frequencies.
"""

from __future__ import annotations

import argparse
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from kws_hw import (  # noqa: E402
    KWSConfig, W_MIN, W_MAX, SKIP, bank_table, bank_report, load_weights,
    corner_hz, CLK_HZ, PDM_HZ, FS, DECIM, PDM_DIV,
)

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "src")
TEST = os.path.join(HERE, "..", "test")


def _hexlit(values, width_bits: int, per_elem: int) -> str:
    """Pack ints little-endian-by-index into one sized SystemVerilog literal.

    Element i occupies bits [i*per_elem +: per_elem], matching the RTL's
    `FLAT[(i*per_elem) +: per_elem]` part-selects.
    """
    acc = 0
    mask = (1 << per_elem) - 1
    for i, v in enumerate(values):
        acc |= (int(v) & mask) << (i * per_elem)
    nib = (width_bits + 3) // 4
    return f"{width_bits}'h{acc:0{nib}x}"


def check_arithmetic(w, bias, cfg: KWSConfig):
    """Fail loudly rather than tape out a design that can silently saturate."""
    w = np.asarray(w, dtype=np.int64)
    bias = np.asarray(bias, dtype=np.int64)
    assert w.shape == (cfg.nclass, cfg.nslot, cfg.nband), w.shape
    assert bias.shape == (cfg.nclass,), bias.shape
    bad = w[(w < W_MIN) | (w > W_MAX)]
    assert bad.size == 0, f"{bad.size} weights outside int4: {bad[:8]}"

    lo, hi = -(1 << (cfg.score_w - 1)), (1 << (cfg.score_w - 1)) - 1
    trim_max = 15 << cfg.trim_shift
    flat = w.reshape(cfg.nclass, -1)
    # Worst case per class: bias (plus the largest trim, on background) and
    # then every negative or every positive weight taken at full feature scale.
    for c in range(cfg.nclass):
        b = int(bias[c]) + (trim_max if c == cfg.nclass - 1 else 0)
        neg = int(np.clip(flat[c], None, 0).sum()) * cfg.feat_max
        pos = int(np.clip(flat[c], 0, None).sum()) * cfg.feat_max
        assert lo <= b + neg and b + pos <= hi, (
            f"class {c}: partial sums span [{b+neg}, {b+pos}], "
            f"outside the {cfg.score_w}-bit accumulator [{lo}, {hi}]")
        assert lo <= b <= hi, f"class {c}: bias {b} does not fit"
    return True


def write_header(w, bias, cfg: KWSConfig, path: str | None = None,
                 note: str = "") -> str:
    """Generate src/kws_weights.svh."""
    path = path or os.path.join(SRC, "kws_weights.svh")
    w = np.asarray(w, dtype=np.int64)
    bias = np.asarray(bias, dtype=np.int64)
    check_arithmetic(w, bias, cfg)

    tbl = bank_table(cfg.nbank)
    sh_bytes = [(int(b) << 4) | int(a) for a, b in tbl]     # pass0 low nibble
    nfeat = cfg.nfeat
    nw = cfg.nclass * nfeat

    lines = [
        "// AUTOGENERATED by train/kws_export.py -- do not edit.",
        "//",
        f"// Keywords : {', '.join(cfg.keywords)} (+ background)",
        f"// Front end: {cfg.nband} bands x {cfg.nslot} slots = {nfeat} features,",
        f"//            feat_w={cfg.feat_w}, frame {1000/cfg.frame_hz:.0f} ms, "
        f"context {cfg.context_ms:.0f} ms",
        f"// Clocking : clk {CLK_HZ/1e6:.3f} MHz -> PDM {PDM_HZ/1e6:.3f} MHz "
        f"(/{PDM_DIV}) -> {FS/1000:.0f} kHz (/{DECIM})",
        "//",
        "// Filterbank corner frequencies (effective pole of the two-pass",
        "// shift-add update, not 2^-a + 2^-b):",
    ]
    for i, (a, b) in enumerate(tbl):
        fc = corner_hz(a, None if b == SKIP else b)
        tag = "anti-alias" if i == 0 else f"band{i-1} upper edge"
        sh = f">>{a}" + ("" if b == SKIP else f" then >>{b}")
        lines.append(f"//   tap {i}: {sh:<16s} fc = {fc:7.1f} Hz   {tag}")
    if note:
        lines += ["//", f"// {note}"]

    lines += [
        "",
        "`ifndef KWS_WEIGHTS_SVH",
        "`define KWS_WEIGHTS_SVH",
        "",
        f"`define KWS_NBANK      {cfg.nbank}",
        f"`define KWS_NSLOT      {cfg.nslot}",
        f"`define KWS_NCLASS     {cfg.nclass}",
        f"`define KWS_FEAT_W     {cfg.feat_w}",
        f"`define KWS_FRAME_LOG2 {cfg.frame_log2}",
        "",
        "// Two shift amounts per tap: pass 0 in the low nibble, pass 1 in the",
        f"// high nibble; 0x{SKIP:x} means that pass is a no-op.",
        f"`define KWS_SH_FLAT {_hexlit(sh_bytes, cfg.nbank*8, 8)}",
        "",
        "// int4 weights, index (class*NFEAT + slot*NBAND + band)",
        f"`define KWS_W_FLAT {_hexlit(w.reshape(cfg.nclass, -1).reshape(-1), nw*4, 4)}",
        "",
        f"// int{cfg.score_w} biases, index class",
        f"`define KWS_B_FLAT {_hexlit(bias, cfg.nclass*cfg.score_w, cfg.score_w)}",
        "",
        "`endif",
        "",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines))
    return path


def write_vectors(cfg: KWSConfig, n: int = 6, seed: int = 5,
                  path: str | None = None):
    """PDM bit stream + expected per-frame decisions, for the cocotb testbench.

    Real speech, run through the real modulator, so the RTL is checked against
    audio rather than against a synthetic pattern that happens to be easy.
    """
    import kws_data as D
    from kws_hw import pdm_decimate, front_end

    path = path or os.path.join(TEST, "kws_vectors.npz")
    rng = np.random.default_rng(seed)
    noise = D.load_noise()

    clips, labels = [], []
    for ci, kw in enumerate(list(cfg.keywords) + [None]):
        if kw is None:
            words = [x for x in D.list_words() if x not in cfg.keywords]
            pick = [os.path.join(D.GSC, words[0]),
                    os.path.join(D.GSC, words[len(words)//2])]
            files = [os.path.join(p, sorted(os.listdir(p))[0]) for p in pick]
        else:
            d = os.path.join(D.GSC, kw)
            files = [os.path.join(d, f) for f in sorted(os.listdir(d))[:n // 3 + 1]]
        for p in files[:max(1, n // 3)]:
            clips.append(D.place(D.read_wav(p), rng, jitter=False))
            labels.append(ci if kw is not None else cfg.nclass - 1)

    clips = np.stack(clips).astype(np.float32)
    labels = np.asarray(labels)

    # The RTL is driven with bits, so save bits -- regenerating the modulator
    # inside the testbench would let the two drift apart.
    from kws_hw import sigma_delta_pdm, upsample_linear
    up = upsample_linear(clips, PDM_HZ // D.SR)
    bits = sigma_delta_pdm(up)
    x = np.stack([np.asarray(
        pdm_decimate(clips[i:i+1], sr_in=D.SR))[0] for i in range(len(clips))])

    np.savez_compressed(
        path, bits=bits.astype(np.uint8), x=x.astype(np.int16),
        labels=labels, cfg=str(cfg.to_dict()))
    return path, bits.shape


# ---------------------------------------------------------------------------
if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--tag", default="default")
    ap.add_argument("--placeholder", default=None,
                    help="nbank,nslot,frame_log2,feat_w -- emit a zero-weight "
                         "header so the RTL compiles before training")
    ap.add_argument("--vectors", action="store_true")
    ap.add_argument("--vector-clips", type=int, default=6)
    a = ap.parse_args()

    if a.placeholder:
        nb, ns, fl, fw = (int(v) for v in a.placeholder.split(","))
        cfg = KWSConfig(nbank=nb, nslot=ns, frame_log2=fl, feat_w=fw)
        w = np.zeros((cfg.nclass, cfg.nslot, cfg.nband), dtype=np.int64)
        b = np.zeros(cfg.nclass, dtype=np.int64)
        p = write_header(w, b, cfg,
                         note="PLACEHOLDER: all weights zero, no model trained.")
        print(f"wrote {p} (placeholder)")
    else:
        w, bias, cfg, blob = load_weights(a.tag)
        acc = blob.get("test_acc")
        note = (f"Speech Commands v0.02 test set: clip accuracy "
                f"{acc*100:.2f}%" if acc else "")
        p = write_header(w, bias, cfg, note=note)
        print(f"wrote {p}")
        print(bank_report(cfg.nbank))
        print(f"\n  weights: {w.size} int4 in [{w.min()}, {w.max()}]")
        print(f"  biases : {bias.tolist()}")
        if a.vectors:
            vp, shape = write_vectors(cfg, n=a.vector_clips)
            print(f"  vectors: {vp} {shape}")
