"""Train the "sheila" spotter that gets hard-wired into tt_um_wakeword.

Fixes over the first attempt, all of which were diagnosed rather than guessed:

  * **Centred features.** Raw features are 0..15 with a large DC, so the
    per-unit bias had to cancel a huge constant before it could do anything
    useful. Training centres them; in silicon this is free, because the
    accumulator resets to a constant anyway -- the offset folds straight into
    that reset value.
  * **Median bias init.** Hidden units start with roughly half their
    pre-activations above zero instead of all-dead.
  * **Leaky straight-through requantiser.** A dead unit still receives 10 % of
    the gradient, so it can come back. Without this the network collapses to
    its bias and sits at chance.
  * **Mean-pool warm-up.** Max-over-window pooling gives gradient to one window
    only; starting on mean pooling and annealing to max avoids the early
    collapse.
  * **Tie-aware AUC.** Scores are small integers, so ties dominate and a strict
    `>` comparison badly understates performance.

    python train/train_sheila.py --tag sheila_hw --arch mlp --emit
"""

from __future__ import annotations

import argparse
import json
import os
import sys

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import wwhw  # noqa: E402

ART = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "artifacts")
SRC = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src")


def emit_weights(W1, HB, W2, thresh, hacc_w, score_w, path, meta):
    """Write ww_weights.svh: hidden template, per-unit reset bias, output layer."""
    H, NF, NB = W1.shape
    code = {0: 0b00, 1: 0b01, -1: 0b11}

    rows = []
    for h in range(H):
        for f in range(NF):
            r = 0
            for b in range(NB):
                r |= code[int(W1[h, f, b])] << (2 * b)
            rows.append(r)
    w1v, w1w = 0, len(rows) * 2 * NB
    for i, r in enumerate(rows):
        w1v |= r << (2 * NB * i)

    hbv, hbw = 0, H * hacc_w
    for h in range(H):
        hbv |= (int(HB[h]) & ((1 << hacc_w) - 1)) << (hacc_w * h)

    w2v = 0
    for h in range(H):
        w2v |= code[int(W2[h])] << (2 * h)

    tv = int(thresh) & ((1 << score_w) - 1)
    nz = int((W1 != 0).sum())
    with open(path, "w") as f:
        f.write("// Auto-generated by train/train_sheila.py -- do not edit.\n")
        f.write(f"// {meta}\n")
        f.write(f"// hidden template {nz}/{W1.size} non-zero ({100*nz/W1.size:.0f}%); "
                "zeros drop out of the adder tree.\n")
        f.write(f"localparam [{w1w-1}:0] WW_ROW      = {w1w}'h{w1v:0{max(w1w//4,1)}x};\n")
        f.write(f"localparam [{hbw-1}:0] WW_HBIAS    = {hbw}'h{hbv:0{max(hbw//4,1)}x};\n")
        f.write(f"localparam [{2*H-1}:0] WW_W2       = {2*H}'h{w2v:0{max(2*H//4,1)}x};\n")
        f.write(f"localparam [{score_w-1}:0] WW_THRESH_PK = {score_w}'h{tv:0{max(score_w//4,1)}x};\n")
        f.write(f"// hidden bias (decimal): {[int(v) for v in HB]}\n")
        f.write(f"// output weights: {[int(v) for v in W2]}   threshold: {int(thresh)}\n")
    return nz


def auc(s, pos):
    """Mann-Whitney with ties counted half."""
    p, n = s[pos], s[~pos]
    return float((p[:, None] > n[None, :]).mean() + 0.5 * (p[:, None] == n[None, :]).mean())


def operating_points(scores, is_pos, hop_frames, frame_ms, fas=(0.5, 1, 5, 20)):
    pos, neg = scores[is_pos], scores[~is_pos]
    order = np.sort(neg)[::-1]
    eph = 3600_000.0 / (hop_frames * frame_ms)
    out = []
    for fa in fas:
        k = fa / eph * len(neg)
        if k < 1:
            thr, floor = float(neg.max()), True
        else:
            thr, floor = float(order[int(k) - 1]), False
        out.append(dict(fa=fa, thr=thr, recall=float((pos > thr).mean()), floor=floor))
    return out, eph


class QW(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, L):
        ctx.save_for_backward(x); ctx.L = L
        return torch.clamp(torch.round(x), -L, L)
    @staticmethod
    def backward(ctx, g):
        (x,) = ctx.saved_tensors
        return g * (x.abs() <= ctx.L + 0.5), None


class SatSTE(torch.autograd.Function):
    """Saturate forward, pass the gradient straight through.

    The RTL clamps the accumulator on *every* frame, not just at the end, so
    training has to do the same or the two diverge whenever a window saturates.
    """
    @staticmethod
    def forward(ctx, x, lim):
        return torch.clamp(x, -lim - 1, lim)
    @staticmethod
    def backward(ctx, g):
        return g, None


class RQ(torch.autograd.Function):
    """clamp(acc >> shift, 0, hi) forward; leaky STE backward."""
    LEAK = 0.1
    @staticmethod
    def forward(ctx, a, s, hi):
        ctx.save_for_backward(a); ctx.s = float(1 << s); ctx.hi = hi
        return torch.clamp(torch.floor(a / ctx.s), 0, hi)
    @staticmethod
    def backward(ctx, g):
        (a,) = ctx.saved_tensors
        z = a / ctx.s
        live = ((z >= 0) & (z <= ctx.hi)).float()
        return g * (live + RQ.LEAK * (1 - live)), None, None


BIAS_LIM = 0   # set in main(): the reset value is a real register


def build(arch, H, NF, NB, WL, Xw, idx):
    """Returns (params, forward, clampers, init_info)."""
    if arch == "linear":
        w = nn.Parameter(torch.empty(1, NF, NB).uniform_(-1.2, 1.2))
        b = nn.Parameter(torch.zeros(1))
        def fwd(x, shift=None, accw=0):
            return torch.einsum('nwfb,kfb->nwk', x, QW.apply(w, WL)) + b
        return [{'params': [w], 'lr': 0.05}, {'params': [b], 'lr': 0.05}], fwd, [w], (w,)

    w1 = nn.Parameter(torch.empty(H, NF, NB).uniform_(-1.2, 1.2))
    with torch.no_grad():
        a0 = torch.einsum('nwfb,hfb->nwh', Xw[idx[:4096]], QW.apply(w1, WL))
        b1v = -a0.reshape(-1, H).median(0).values
        if BIAS_LIM:
            b1v = b1v.clamp(-BIAS_LIM - 1, BIAS_LIM)
    b1 = nn.Parameter(b1v.clone())
    w2 = nn.Parameter(torch.tensor([[1.0 if h % 2 == 0 else -1.0 for h in range(H)]]))
    b = nn.Parameter(torch.zeros(1))

    def fwd(x, shift, accw=0):
        q1 = QW.apply(w1, WL)
        if accw:
            # Frame by frame, saturating each step -- exactly the RTL's loop.
            lim = (1 << (accw - 1)) - 1
            a = torch.round(b1).expand(x.shape[0], x.shape[1], -1)
            for f in range(x.shape[2]):
                a = SatSTE.apply(a + torch.einsum('nwb,hb->nwh', x[:, :, f, :],
                                                  q1[:, f, :]), lim)
        else:
            a = torch.einsum('nwfb,hfb->nwh', x, q1) + b1
        h = RQ.apply(a, shift, 15)
        return torch.einsum('nwh,kh->nwk', h, QW.apply(w2, WL)) + b

    groups = [{'params': [w1], 'lr': 0.08}, {'params': [b1], 'lr': 0.5},
              {'params': [w2], 'lr': 0.02}, {'params': [b], 'lr': 0.02}]
    return groups, fwd, [w1, w2], (w1, b1, w2, b)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tag", default="sheila_hw")
    ap.add_argument("--arch", choices=["linear", "mlp", "both"], default="both")
    ap.add_argument("--H", type=int, default=8)
    ap.add_argument("--WL", type=int, default=1, help="1=ternary, 3=int3, 7=int4")
    ap.add_argument("--shift", type=int, default=2)
    ap.add_argument("--nphase", type=int, default=0, help="0 = use cfg")
    ap.add_argument("--merge2", action="store_true",
                    help="pair adjacent frames by max -> FRAME_LOG2+1, half the "
                         "weight ROM. Exact: max over 2^(F+1) ticks is the max "
                         "of two consecutive max-over-2^F values.")
    ap.add_argument("--nframe", type=int, default=0, help="0 = cfg.nframe")
    ap.add_argument("--accw", type=int, default=0, help="saturating hidden acc width")
    ap.add_argument("--epochs", type=int, default=150)
    ap.add_argument("--warmup", type=float, default=0.4, help="fraction on mean pooling")
    ap.add_argument("--fa", type=float, default=1.0)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--emit", action="store_true")
    args = ap.parse_args()

    d = np.load(os.path.join(ART, f"ww_feats_{args.tag}.npz"), allow_pickle=True)
    feats, labels, splits = d["feats"], d["labels"], d["splits"]
    cfg = wwhw.HWConfig(**json.loads(str(d["cfg"])))
    if args.merge2:
        t = feats.shape[1] // 2 * 2
        feats = np.maximum(feats[:, 0:t:2], feats[:, 1:t:2])
        cfg.frame_log2 += 1
    NB = cfg.nband
    NF = args.nframe or cfg.nframe
    nphase = args.nphase or cfg.nphase
    hop = NF // nphase
    starts = list(range(0, feats.shape[1] - NF + 1, hop))
    CENTRE = int(round(feats[splits == 0].mean()))   # any constant works; the
                                                     # mean just conditions training

    global BIAS_LIM
    BIAS_LIM = ((1 << (args.accw - 1)) - 1) if args.accw else 0
    # The chip subtracts this constant from each band feature before the
    # adder tree (parameter FEAT_OFF) -- one constant subtract on a 4-bit
    # value. That keeps both the accumulator and the reset bias small.
    CENTRE = int(round(feats[splits == 0].mean()))
    X = feats.astype(np.float32) - CENTRE
    Xw = torch.from_numpy(np.stack([X[:, s:s + NF] for s in starts], 1))
    Y = torch.from_numpy((labels > 0).astype(np.float32))[:, None]
    tr, va, te = splits == 0, splits == 1, splits == 2
    idx = np.where(tr)[0]
    print(f"tag={args.tag}  {feats.shape}  bands={NB}  window={NF} frames "
          f"({NF*cfg.frame_ms:.0f} ms)  phases={nphase}  hop={hop}")
    print(f"FEAT_OFF={CENTRE} subtracted in hardware; hidden bias range +-{BIAS_LIM}")
    print(f"train {tr.sum()} / val {va.sum()} / test {te.sum()}   "
          f"positives {int((labels>0).sum())}")

    results = {}
    archs = ["linear", "mlp"] if args.arch == "both" else [args.arch]
    for arch in archs:
        torch.manual_seed(args.seed); np.random.seed(args.seed)
        groups, fwd, clampers, tensors = build(arch, args.H, NF, NB, args.WL, Xw, idx)
        lt = nn.Parameter(torch.tensor(2.0)); groups.append({'params': [lt], 'lr': 0.01})
        opt = torch.optim.Adam(groups)
        sch = torch.optim.lr_scheduler.CosineAnnealingLR(opt, args.epochs)
        nwarm = int(args.warmup * args.epochs)
        best = (-1, None)
        for ep in range(args.epochs):
            for i in range(0, len(idx), 1024):
                j = np.random.permutation(idx)[i:i + 1024] if i == 0 else idx[i:i + 1024]
                s = fwd(Xw[j], args.shift, args.accw)
                pooled = (s.mean(1) if ep < nwarm
                          else s.logsumexp(1) - np.log(s.shape[1]))
                loss = F.binary_cross_entropy_with_logits(pooled / torch.exp(lt), Y[j])
                opt.zero_grad(); loss.backward(); opt.step()
                with torch.no_grad():
                    for c in clampers:
                        c.clamp_(-(args.WL + 0.5), args.WL + 0.5)
                    if BIAS_LIM and arch == "mlp":
                        tensors[1].clamp_(-BIAS_LIM - 1, BIAS_LIM)
            sch.step()
            if (ep + 1) % 25 == 0 or ep == args.epochs - 1:
                with torch.no_grad():
                    sv = fwd(Xw, args.shift, args.accw).max(1).values[:, 0].numpy()
                a = auc(sv[va], (labels > 0)[va])
                if a > best[0]:
                    best = (a, [t.detach().clone() for t in tensors])
                print(f"  [{arch}] ep {ep+1:4d}  loss {loss.item():.4f}  val AUC {a*100:5.1f}%")
        with torch.no_grad():
            for t, bv in zip(tensors, best[1]):
                t.copy_(bv)
            sv = fwd(Xw, args.shift, args.accw).max(1).values[:, 0].numpy()
        ate = auc(sv[te], (labels > 0)[te])
        ops, eph = operating_points(sv[te], (labels > 0)[te], hop, cfg.frame_ms)
        vops, _ = operating_points(sv[va], (labels > 0)[va], hop, cfg.frame_ms, (args.fa,))
        print(f"  [{arch}] TEST AUC {ate*100:.2f}%   ({eph:.0f} windows/hour)")
        for o in ops:
            fl = "  [below measurement floor]" if o["floor"] else ""
            print(f"        recall @ {o['fa']:5.1f} FA/h = {o['recall']*100:5.1f}% "
                  f"(thr {o['thr']:.0f}){fl}")
        results[arch] = dict(auc=ate, ops=ops, thr=int(np.floor(vops[0]["thr"])),
                             tensors=[t.detach().clone() for t in tensors])

    pick = max(results, key=lambda k: results[k]["auc"])
    print(f"\nbest: {pick}  AUC {results[pick]['auc']*100:.2f}%")

    if args.emit:
        assert pick == "mlp", "emit expects the mlp head"
        t = results["mlp"]["tensors"]
        W1 = QW.apply(t[0], args.WL).numpy().astype(np.int64)
        b1 = t[1].numpy()
        W2 = QW.apply(t[2], args.WL).numpy().astype(np.int64).reshape(-1)
        bo = float(t[3].numpy().reshape(-1)[0])
        # Centring folds into the per-unit reset value; the output bias folds
        # into the threshold. Both are exact, not approximations.
        HB = np.round(b1).astype(np.int64)
        if BIAS_LIM:
            assert HB.min() >= -BIAS_LIM - 1 and HB.max() <= BIAS_LIM, (
                f'hidden bias {HB} outside the accumulator range')
        thr = int(np.floor(results["mlp"]["thr"] - bo))
        emit_weights(W1, HB, W2, thr, args.accw or 8, 10,
                     os.path.join(SRC, "ww_weights.svh"),
                     f"sheila, H={args.H} ternary, AUC {results['mlp']['auc']*100:.1f}%, "
                     f"nphase={nphase} shift={args.shift} centre={CENTRE}")
        print(f"wrote {os.path.relpath(os.path.join(SRC,'ww_weights.svh'))}  "
              f"HBIAS={HB.tolist()}  W2={W2.tolist()}  thr={thr}")

    np.savez(os.path.join(ART, f"ww_sheila_{args.arch}_{args.tag}.npz"),
             **{f"t{i}": t.numpy() for i, t in enumerate(results[pick]["tensors"])},
             auc=results[pick]["auc"], centre=CENTRE, cfg=json.dumps(cfg.to_dict()))


if __name__ == "__main__":
    main()
