// AUTOGENERATED by train/kws_export.py -- do not edit.
//
// Keywords : marvin, sheila (+ background)
// Front end: 4 bands x 4 slots = 16 features,
//            feat_w=4, frame 85 ms, context 341 ms
// Clocking : clk 12.288 MHz -> PDM 3.072 MHz (/4) -> 48 kHz (/64)
//
// Filterbank corner frequencies (effective pole of the two-pass
// shift-add update, not 2^-a + 2^-b):
//   tap 0: >>1              fc =  3819.7 Hz   anti-alias
//   tap 1: >>3 then >>3     fc =  1790.5 Hz   band0 upper edge
//   tap 2: >>4 then >>5     fc =   701.3 Hz   band1 upper edge
//   tap 3: >>5 then >>6     fc =   354.4 Hz   band2 upper edge
//   tap 4: >>6 then >>8     fc =   148.7 Hz   band3 upper edge
//
// Speech Commands v0.02 test set: clip accuracy 36.54%

`ifndef KWS_WEIGHTS_SVH
`define KWS_WEIGHTS_SVH

`define KWS_NBANK      5
`define KWS_NSLOT      4
`define KWS_NCLASS     3
`define KWS_FEAT_W     4
`define KWS_FRAME_LOG2 12

// Two shift amounts per tap: pass 0 in the low nibble, pass 1 in the
// high nibble; 0xf means that pass is a no-op.
`define KWS_SH_FLAT 40'h86655433f1

// int4 weights, index (class*NFEAT + slot*NBAND + band)
`define KWS_W_FLAT 192'h10ffdecd644e211d1000f1000011af24420f4fde61eebff2

// int16 biases, index class
`define KWS_B_FLAT 48'h0018ffeaffe7

`endif
