// SPDX-FileCopyrightText: 2026
// SPDX-License-Identifier: Apache-2.0
//
// tt_um_kws -- host-free keyword spotter for a TinyTapeout IHP 1x1 tile.
//
// A PDM microphone goes in one pin and an LED comes out. There is no host, no
// weight streaming and no SRAM: the classifier weights are combinational
// constants baked in at tapeout (src/kws_weights.svh, generated by
// train/kws_export.py) and every stateful element fits in ~270 flip-flops,
// which is what a 1x1 tile can afford (see docs/design-space-1x1.md).
//
//   pdm_data  --1 bit @ 3.072 MHz-->  count ones over DECIM bits
//     --> x, 7-bit signed @ 48 kHz
//     --> NBANK cascaded one-pole leaky integrators, shift-add only
//     --> NBAND = NBANK-1 bands as differences of adjacent taps
//     --> leaky peak envelope per band
//     --> log magnitude by leading-one position (FEAT_W bits)
//     --> max-pool into NSLOT time slots
//     --> int4 linear classifier over NBAND*NSLOT features
//     --> argmax, hold, LED.
//
// There is no multiplier in the front end. Each integrator coefficient is
// applied as up to two sequential shift-add passes over the same register, so
// the effective pole is 1-(1-2^-a)(1-2^-b) rather than 2^-a+2^-b -- see
// `alpha_effective` in train/kws_hw.py, the golden model this is bit-exact
// against.
//
// Timing: one 48 kHz sample is 256 clocks at 12.288 MHz. The sequencer needs
// 2*NBANK + NBAND cycles every sample plus NCLASS*NFEAT once per frame, i.e.
// 62 of 256 in the default build, so nothing is ever rate-limited.

`default_nettype none

`include "kws_weights.svh"

module tt_um_kws #(
    // ---- front end ----
    // Integrator taps. NBAND = NBANK-1 bands; tap 0 doubles as the anti-alias
    // low-pass that keeps shaped PDM noise out of the top band.
    parameter NBANK      = `KWS_NBANK,
    // Integrator register width. IN_SHIFT=7 on a 7-bit x gives |u| <= 4096,
    // and a one-pole has unity DC gain with no overshoot, so |y| <= |u| and a
    // 14-bit register cannot overflow.
    parameter STATE_W    = 14,
    parameter IN_SHIFT   = 7,
    parameter ENV_W      = 12,
    parameter ENV_SHIFT  = 2,
    parameter DECAY      = 9,
    // 4 = leading-one position only (6 dB per step, free in gates).
    // 5 = plus the bit below it (3 dB per step, NBAND*NSLOT more flops).
    parameter FEAT_W     = `KWS_FEAT_W,
    // ---- temporal ----
    parameter NSLOT      = `KWS_NSLOT,
    parameter FRAME_LOG2 = `KWS_FRAME_LOG2,
    // ---- classifier ----
    parameter NCLASS     = `KWS_NCLASS,
    parameter SCORE_W    = 16,
    // Trim step size. Trained score margins are tens, not hundreds, so a
    // step of 2 (TRIM_SHIFT=1) spans a useful sensitivity range across the
    // nibble; the original 6 gave +128 per step, which took the chip from
    // trigger-happy to permanently deaf between trim=1 and trim=2.
    parameter TRIM_SHIFT = 1,
    parameter HOLD_FRAMES = 6,
    // ---- microphone interface ----
    parameter PDM_DIV    = 4,      // clk / PDM_DIV = PDM bit clock
    parameter DECIM      = 64      // PDM bits per 48 kHz sample
) (
    input  wire [7:0] ui_in,    // dedicated inputs
    output wire [7:0] uo_out,   // dedicated outputs
    input  wire [7:0] uio_in,   // IOs: input path  (unused)
    output wire [7:0] uio_out,  // IOs: output path (all outputs)
    output wire [7:0] uio_oe,   // IOs: enable
    input  wire       ena,      // always 1 when powered -- unused
    input  wire       clk,
    input  wire       rst_n
);

  localparam int NBAND = NBANK - 1;
  localparam int NFEAT = NBAND * NSLOT;
  localparam int NW    = NCLASS * NFEAT;

  localparam int BIDX_W = (NBANK  <= 2)  ? 1 : (NBANK  <= 4)  ? 2 :
                          (NBANK  <= 8)  ? 3 : 4;
  localparam int SIDX_W = (NSLOT  <= 2)  ? 1 : (NSLOT  <= 4)  ? 2 : 3;
  localparam int CIDX_W = (NCLASS <= 2)  ? 1 : (NCLASS <= 4)  ? 2 : 3;
  localparam int FIDX_W = (NFEAT  <= 16) ? 4 : (NFEAT  <= 32) ? 5 : 6;
  localparam int DEC_W  = (DECIM  <= 32) ? 5 : (DECIM  <= 64) ? 6 : 7;
  localparam int ONES_W = DEC_W + 1;
  localparam int X_W    = DEC_W + 1;          // signed [-DECIM/2, +DECIM/2]
  localparam int PDIV_W = (PDM_DIV <= 2) ? 1 : (PDM_DIV <= 4) ? 2 : 3;
  localparam int HOLD_W = 4;
  // Intermediate widths are sized exactly, not padded to a convenient 32.
  // Saturation compares every bit of its argument, so yosys cannot prove wide
  // upper bits dead: a 32-bit d_tap costs a 32-bit subtractor and a 4-stage
  // 32-bit barrel shifter where 15 bits would do.
  localparam int UW     = X_W + IN_SHIFT;     // x << IN_SHIFT, exact
  localparam int DW     = STATE_W + 1;        // prev - y, exact
  localparam int YW     = STATE_W + 2;        // y + (d >>> sh), exact
  localparam int AW     = SCORE_W + 1;        // acc + product, exact

  localparam logic [ENV_W-1:0]  ENV_MAX  = {ENV_W{1'b1}};
  localparam logic [FEAT_W-1:0] FEAT_MAX = {FEAT_W{1'b1}};
  localparam int STATE_HI =  (1 << (STATE_W-1)) - 1;
  localparam int STATE_LO = -(1 << (STATE_W-1));
  localparam int SCORE_HI =  (1 << (SCORE_W-1)) - 1;
  localparam int SCORE_LO = -(1 << (SCORE_W-1));
  localparam logic [3:0] SH_SKIP = 4'hF;

  // ---------------------------------------------------------------------
  // Saturating helpers. The golden model clamps at exactly these points.
  // ---------------------------------------------------------------------
  function automatic logic signed [STATE_W-1:0] sat_state(
      input logic signed [YW-1:0] v);
    if (v > STATE_HI)      sat_state = STATE_W'(STATE_HI);
    else if (v < STATE_LO) sat_state = STATE_W'(STATE_LO);
    else                   sat_state = v[STATE_W-1:0];
  endfunction

  function automatic logic signed [SCORE_W-1:0] sat_score(
      input logic signed [AW-1:0] v);
    if (v > SCORE_HI)      sat_score = SCORE_W'(SCORE_HI);
    else if (v < SCORE_LO) sat_score = SCORE_W'(SCORE_LO);
    else                   sat_score = v[SCORE_W-1:0];
  endfunction

  function automatic logic signed [STATE_W-1:0] sat_in(
      input logic signed [UW-1:0] v);
    if (v > STATE_HI)      sat_in = STATE_W'(STATE_HI);
    else if (v < STATE_LO) sat_in = STATE_W'(STATE_LO);
    else                   sat_in = v[STATE_W-1:0];
  endfunction

  // ---------------------------------------------------------------------
  // Filterbank microcode: two shift amounts per tap, SH_SKIP = no-op pass.
  // Laid out so that the pair (tap, pass) is just a flat nibble index.
  // ---------------------------------------------------------------------
  localparam logic [NBANK*8-1:0] SH_FLAT = `KWS_SH_FLAT;

  // ---------------------------------------------------------------------
  // Weight constants. When the generated header was built for different
  // dimensions than the parameters ask for -- exactly what happens during an
  // area sweep -- fall back to a deterministic LFSR filler so synthesis still
  // reports a meaningful cell count instead of optimising the design away.
  // ---------------------------------------------------------------------
  localparam bit DIMS_OK = (`KWS_NBANK == NBANK) && (`KWS_NSLOT == NSLOT) &&
                           (`KWS_NCLASS == NCLASS) && (`KWS_FEAT_W == FEAT_W);

  function automatic logic [NW*4-1:0] w_filler();
    logic [15:0] lfsr;
    lfsr = 16'hACE1;
    for (int i = 0; i < NW*4; i++) begin
      w_filler[i] = lfsr[0];
      lfsr = {lfsr[0] ^ lfsr[2] ^ lfsr[3] ^ lfsr[5], lfsr[15:1]};
    end
  endfunction

  localparam logic [NW*4-1:0]           W_FLAT = DIMS_OK ? `KWS_W_FLAT : w_filler();
  localparam logic [NCLASS*SCORE_W-1:0] B_FLAT = DIMS_OK ? `KWS_B_FLAT : '0;

  // ---------------------------------------------------------------------
  // Pins
  // ---------------------------------------------------------------------
  wire       pdm_data  = ui_in[0];
  wire [3:0] sens_trim = ui_in[4:1];   // raises the background bias
  wire [2:0] dbg_band  = ui_in[7:5];

  // ---------------------------------------------------------------------
  // Microphone clock and ones-counting decimator
  // ---------------------------------------------------------------------
  logic [PDIV_W-1:0]     pdiv;
  logic [ONES_W-1:0]     ones;
  logic [DEC_W-1:0]      dec_cnt;
  logic signed [X_W-1:0] x;
  logic                  sample_start;

  wire pdm_clk  = pdiv[PDIV_W-1];
  // Sample right after the falling edge, safely inside the bit's valid window.
  wire pdm_samp = (pdiv == '0);
  wire dec_last = (dec_cnt == DEC_W'(DECIM - 1));
  wire [ONES_W-1:0] ones_next = ones + {{(ONES_W-1){1'b0}}, pdm_data};

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      pdiv <= '0; ones <= '0; dec_cnt <= '0; x <= '0; sample_start <= 1'b0;
    end else begin
      pdiv <= pdiv + 1'b1;
      sample_start <= 1'b0;
      if (pdm_samp) begin
        dec_cnt <= dec_cnt + 1'b1;
        if (dec_last) begin
          // centre the count: an all-zero stream is -DECIM/2, all-ones +DECIM/2
          x <= X_W'($signed({1'b0, ones_next}) - $signed((X_W+1)'(DECIM/2)));
          ones <= '0;
          sample_start <= 1'b1;
        end else begin
          ones <= ones_next;
        end
      end
    end
  end

  // ---------------------------------------------------------------------
  // State
  // ---------------------------------------------------------------------
  logic signed [STATE_W-1:0] y   [NBANK];
  logic        [ENV_W-1:0]   env [NBAND];
  logic        [FEAT_W-1:0]  slot[NSLOT][NBAND];

  logic [FRAME_LOG2-1:0]     frame_cnt;
  logic signed [SCORE_W-1:0] acc, best;
  logic [CIDX_W-1:0]         best_cls;
  logic [HOLD_W-1:0]         hold [NCLASS-1];

  logic [BIDX_W-1:0] bi;      // filterbank tap / envelope band index
  logic              pass;    // which shift-add pass of the current tap
  logic [CIDX_W-1:0] ci;      // classifier class index
  logic [FIDX_W-1:0] fi;      // classifier feature index
  logic              frame_due, samp_pending;
  logic              env_sat, score_sat;
  logic              frame_tick, frame_strobe;

  localparam logic [1:0] S_IDLE = 2'd0, S_FILT = 2'd1,
                         S_ENV  = 2'd2, S_CLS  = 2'd3;
  logic [1:0] state;

  // ---- input to the cascade, sign-extended, scaled and saturated
  wire signed [UW-1:0] u_wide = $signed({{IN_SHIFT{x[X_W-1]}}, x}) <<< IN_SHIFT;
  wire signed [STATE_W-1:0] u = sat_in(u_wide);

  // ---------------------------------------------------------------------
  // Filterbank step: y[bi] += (prev - y[bi]) >>> shift
  // ---------------------------------------------------------------------
  logic signed [STATE_W-1:0] prev_tap, y_cur;
  always_comb begin
    prev_tap = u;
    y_cur    = '0;
    for (int i = 0; i < NBANK; i++) begin
      if (BIDX_W'(i) == bi) y_cur = y[i];
      if (i > 0 && BIDX_W'(i) == bi) prev_tap = y[i-1];
    end
  end

  wire [BIDX_W:0] sh_idx = {bi, pass};
  wire [3:0] sh_now = SH_FLAT[(32'(sh_idx) * 4) +: 4];

  wire signed [DW-1:0] d_tap = $signed({prev_tap[STATE_W-1], prev_tap})
                             - $signed({y_cur[STATE_W-1], y_cur});
  wire signed [DW-1:0] d_sh  = d_tap >>> sh_now;
  wire signed [YW-1:0] y_sum = $signed({{2{y_cur[STATE_W-1]}}, y_cur})
                             + $signed({d_sh[DW-1], d_sh});
  wire signed [STATE_W-1:0] y_next = sat_state(y_sum);

  // ---------------------------------------------------------------------
  // Envelope step and log feature
  // ---------------------------------------------------------------------
  logic signed [STATE_W-1:0] y_lo, y_hi;
  logic [ENV_W-1:0]          env_cur;
  logic [FEAT_W-1:0]         slot0_cur;
  always_comb begin
    y_hi = '0; y_lo = '0; env_cur = '0; slot0_cur = '0;
    for (int i = 0; i < NBAND; i++)
      if (BIDX_W'(i) == bi) begin
        y_hi = y[i]; y_lo = y[i+1];
        env_cur = env[i]; slot0_cur = slot[0][i];
      end
  end

  wire signed [STATE_W:0] band_s   = $signed({y_hi[STATE_W-1], y_hi})
                                   - $signed({y_lo[STATE_W-1], y_lo});
  wire [STATE_W:0] band_abs        = band_s[STATE_W] ? (~band_s + 1'b1)
                                                     : band_s;
  wire [STATE_W:0] band_scaled     = band_abs >> ENV_SHIFT;
  wire             env_over        = |band_scaled[STATE_W:ENV_W];
  wire [ENV_W-1:0] env_in          = env_over ? ENV_MAX : band_scaled[ENV_W-1:0];

  // Decay by env>>DECAY but never by less than one LSB, otherwise a small
  // envelope would shift down to zero and then never fall the rest of the way.
  wire [ENV_W-1:0] env_shr  = env_cur >> DECAY;
  wire [ENV_W-1:0] env_step = (env_cur == '0) ? '0
                            : (env_shr == '0) ? {{(ENV_W-1){1'b0}}, 1'b1}
                                              : env_shr;
  wire [ENV_W-1:0] env_dec  = env_cur - env_step;
  wire [ENV_W-1:0] env_next = (env_in > env_dec) ? env_in : env_dec;

  // Leading-one position of env_next: 0 when zero, ENV_W when the top bit is
  // set. This priority encoder *is* the logarithm -- the whole reason the
  // features are cheap.
  logic [4:0] lead;
  always_comb begin
    lead = '0;
    for (int i = 0; i < ENV_W; i++)
      if (env_next[i]) lead = 5'(i + 1);
  end

  // Mantissa bit for FEAT_W == 5: the bit immediately below the leading one.
  logic mant;
  always_comb begin
    mant = 1'b0;
    for (int i = 0; i < ENV_W; i++)
      if (lead >= 5'd2 && 5'(i) == (lead - 5'd2)) mant = env_next[i];
  end

  wire [5:0] feat_raw  = (FEAT_W == 5) ? {lead, mant} : {1'b0, lead};
  wire [5:0] feat_cap  = {{(6-FEAT_W){1'b0}}, FEAT_MAX};
  wire [FEAT_W-1:0] feat_now = (feat_raw > feat_cap) ? FEAT_MAX
                                                    : feat_raw[FEAT_W-1:0];
  wire [FEAT_W-1:0] slot0_next = (feat_now > slot0_cur) ? feat_now : slot0_cur;

  // ---------------------------------------------------------------------
  // Classifier step: acc += weight(ci, fi) * feature(fi)
  // Feature index is slot*NBAND + band, matching the golden model's reshape.
  // ---------------------------------------------------------------------
  logic [FEAT_W-1:0] feat_sel;
  always_comb begin
    feat_sel = '0;
    for (int s = 0; s < NSLOT; s++)
      for (int b = 0; b < NBAND; b++)
        if (FIDX_W'(s*NBAND + b) == fi) feat_sel = slot[s][b];
  end

  logic signed [3:0]         w_sel;
  logic signed [SCORE_W-1:0] bias_sel;
  always_comb begin
    w_sel    = '0;
    bias_sel = '0;
    for (int c = 0; c < NCLASS; c++) begin
      if (CIDX_W'(c) == ci) bias_sel = B_FLAT[(c*SCORE_W) +: SCORE_W];
      for (int f = 0; f < NFEAT; f++)
        if (CIDX_W'(c) == ci && FIDX_W'(f) == fi)
          w_sel = W_FLAT[((c*NFEAT + f)*4) +: 4];
    end
  end

  // The last class is background; the ui trim nibble makes it harder to beat,
  // so a bigger trim value means a less trigger-happy chip.
  // The trim nibble only ever shifts the background bias up, so a 4-bit adder
  // at bit TRIM_SHIFT is enough -- no wide add, no second saturator.
  wire [3:0] trim_n = (ci == CIDX_W'(NCLASS-1)) ? sens_trim : 4'd0;
  wire signed [AW-1:0] bias_trimmed =
      $signed({bias_sel[SCORE_W-1], bias_sel})
      + $signed({{(AW-4-TRIM_SHIFT){1'b0}}, trim_n, {TRIM_SHIFT{1'b0}}});

  wire signed [SCORE_W-1:0] acc_base = (fi == '0) ? sat_score(bias_trimmed) : acc;
  wire signed [FEAT_W+4:0]  prod     = $signed({1'b0, feat_sel}) * w_sel;
  wire signed [AW-1:0]      acc_sum  =
      $signed({acc_base[SCORE_W-1], acc_base})
      + $signed({{(AW-FEAT_W-5){prod[FEAT_W+4]}}, prod});
  wire signed [SCORE_W-1:0] acc_next = sat_score(acc_sum);
  wire acc_would_sat = (acc_sum > SCORE_HI) || (acc_sum < SCORE_LO);

  // ---------------------------------------------------------------------
  // Sequencer
  // ---------------------------------------------------------------------
  wire filt_last      = (bi == BIDX_W'(NBANK-1)) && pass;
  wire env_last       = (bi == BIDX_W'(NBAND-1));
  wire cls_score_done = (fi == FIDX_W'(NFEAT-1));
  wire cls_last       = (ci == CIDX_W'(NCLASS-1)) && cls_score_done;

  // Winner including the class that is completing this cycle, so the hold
  // registers can be updated in the same cycle the last score lands.
  wire beats_best = (ci == '0) || (acc_next > best);
  wire [CIDX_W-1:0] fin_cls = beats_best ? ci : best_cls;

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      state <= S_IDLE;
      bi <= '0; pass <= 1'b0; ci <= '0; fi <= '0;
      frame_cnt <= '0; frame_due <= 1'b0; samp_pending <= 1'b0;
      acc <= '0; best <= '0; best_cls <= CIDX_W'(NCLASS-1);
      env_sat <= 1'b0; score_sat <= 1'b0;
      frame_tick <= 1'b0; frame_strobe <= 1'b0;
      for (int i = 0; i < NBANK; i++) y[i] <= '0;
      for (int i = 0; i < NBAND; i++) env[i] <= '0;
      for (int s = 0; s < NSLOT; s++)
        for (int b = 0; b < NBAND; b++) slot[s][b] <= '0;
      for (int c = 0; c < NCLASS-1; c++) hold[c] <= '0;
    end else begin
      frame_strobe <= 1'b0;
      // A sample can arrive while the classifier is still running (it cannot
      // at the nominal clock, but a slow clock must degrade gracefully rather
      // than silently drop audio).
      if (sample_start && state != S_IDLE) samp_pending <= 1'b1;

      case (state)
        // -----------------------------------------------------------
        S_IDLE: if (sample_start || samp_pending) begin
          samp_pending <= 1'b0;
          state <= S_FILT;
          bi <= '0; pass <= 1'b0;
          frame_due <= (frame_cnt == {FRAME_LOG2{1'b1}});
          frame_cnt <= frame_cnt + 1'b1;
        end

        // -----------------------------------------------------------
        S_FILT: begin
          if (sh_now != SH_SKIP)
            for (int i = 0; i < NBANK; i++)
              if (BIDX_W'(i) == bi) y[i] <= y_next;
          if (filt_last) begin
            state <= S_ENV; bi <= '0;
          end else if (pass) begin
            pass <= 1'b0; bi <= bi + 1'b1;
          end else begin
            pass <= 1'b1;
          end
        end

        // -----------------------------------------------------------
        S_ENV: begin
          for (int i = 0; i < NBAND; i++)
            if (BIDX_W'(i) == bi) begin
              env[i]     <= env_next;
              slot[0][i] <= slot0_next;
            end
          if (env_over) env_sat <= 1'b1;
          if (env_last) begin
            if (frame_due) begin
              state <= S_CLS; ci <= '0; fi <= '0;
            end else begin
              state <= S_IDLE;
            end
          end else begin
            bi <= bi + 1'b1;
          end
        end

        // -----------------------------------------------------------
        // One class at a time through a single accumulator, then argmax.
        S_CLS: begin
          acc <= acc_next;
          if (acc_would_sat) score_sat <= 1'b1;

          if (cls_score_done) begin
            if (beats_best) begin
              best <= acc_next; best_cls <= ci;
            end
            fi <= '0;
            if (cls_last) begin
              // ---- end of frame: age the holds, latch the winner, then
              // ---- shift the slot register and clear the newest slot.
              for (int c = 0; c < NCLASS-1; c++)
                if (|hold[c]) hold[c] <= hold[c] - 1'b1;
              for (int c = 0; c < NCLASS-1; c++)
                if (CIDX_W'(c) == fin_cls) hold[c] <= HOLD_W'(HOLD_FRAMES);

              for (int s = NSLOT-1; s > 0; s--)
                for (int b = 0; b < NBAND; b++) slot[s][b] <= slot[s-1][b];
              for (int b = 0; b < NBAND; b++) slot[0][b] <= '0;

              frame_tick   <= ~frame_tick;
              frame_strobe <= 1'b1;
              frame_due    <= 1'b0;
              state        <= S_IDLE;
            end else begin
              ci <= ci + 1'b1;
            end
          end else begin
            fi <= fi + 1'b1;
          end
        end

        default: state <= S_IDLE;
      endcase
    end
  end

  // ---------------------------------------------------------------------
  // Outputs
  // ---------------------------------------------------------------------
  logic [1:0] det;
  always_comb begin
    det = '0;
    for (int c = 0; c < NCLASS-1; c++)
      if (c < 2) det[c] = |hold[c];
  end

  logic [FEAT_W-1:0] dbg_feat;
  always_comb begin
    dbg_feat = '0;
    for (int b = 0; b < NBAND; b++)
      if (3'(b) == dbg_band) dbg_feat = slot[0][b];
  end
  // Width cast, not a padded concatenation: {{(4-FEAT_W){1'b0}}, ...} is a
  // zero-width replication when FEAT_W == 4, which is illegal and quietly
  // corrupts the enclosing concatenation.
  wire [3:0] dbg_nibble = (FEAT_W >= 4) ? 4'(dbg_feat >> (FEAT_W - 4))
                                        : 4'(dbg_feat << (4 - FEAT_W));

  assign uo_out = {dbg_nibble,        // [7:4] live band level, pick with ui[7:5]
                   frame_tick,        // [3]   toggles once per frame
                   |det,              // [2]   any keyword
                   det[1],            // [1]   keyword 1
                   det[0]};           // [0]   keyword 0

  assign uio_out = {sample_start,     // [7] 48 kHz sample strobe
                    score_sat,        // [6] sticky: classifier saturated
                    env_sat,          // [5] sticky: envelope saturated
                    pdm_data,         // [4] echo of the mic bit, for bring-up
                    2'(best_cls),     // [3:2] argmax class
                    frame_strobe,     // [1] one-clock pulse per frame
                    pdm_clk};         // [0] microphone bit clock
  assign uio_oe = 8'hFF;

  wire _unused = &{ena, uio_in, 1'b0};

`ifndef SYNTHESIS
  initial begin
    if (!DIMS_OK)
      $display({"tt_um_kws: NOTE kws_weights.svh is for %0d/%0d/%0d/%0d ",
                "(NBANK/NSLOT/NCLASS/FEAT_W) but this build is %0d/%0d/%0d/%0d",
                " -- using LFSR filler weights, valid for area sweeps only"},
               `KWS_NBANK, `KWS_NSLOT, `KWS_NCLASS, `KWS_FEAT_W,
               NBANK, NSLOT, NCLASS, FEAT_W);
    if (2*NBANK + NBAND + NCLASS*NFEAT > PDM_DIV*DECIM)
      $fatal(1, "tt_um_kws: sequencer needs %0d cycles, a sample is only %0d",
             2*NBANK + NBAND + NCLASS*NFEAT, PDM_DIV*DECIM);
  end
`endif

endmodule
