// Auto-generated by train/train_sheila.py -- do not edit.
// drone, H=4 ternary, AUC 95.3%, nphase=2 shift=1 centre=6
// hidden template 245/320 non-zero (77%); zeros drop out of the adder tree.
localparam [639:0] WW_ROW      = 640'hffffffffffcff3f0fc7fdfc7f1fc7f5fd7f13d4f5054340574417415c050101701c10d415015d530d4751d375dc7751d5751d4751d5755d4755d5755551545515411357d7f44dd347c330cffffffc3ff;
localparam [23:0] WW_HBIAS    = 24'h039042;
localparam [7:0] WW_W2       = 8'hdf;
localparam [9:0] WW_THRESH_PK = 10'h3ff;
// hidden bias (decimal): [2, 1, -7, 0]
// output weights: [-1, -1, 1, -1]   threshold: -1  (validation clip FPR 5%, set by eval_header.py --set-fpr)
