// Auto-generated by train/train_sheila.py -- do not edit.
// sheila, H=4 WL=1, AUC 94.9%, nphase=2 shift=1 centre=7 nframe=8
// hidden template 118/160 non-zero (74%); zeros drop out of the adder tree.
localparam [319:0] WW_ROW      = 320'hf035f55d5457d3f4fd7f57d555411dd431cc37d1c4053d003d5d5f54c17fc51545cc3cffffc31107;
localparam [23:0] WW_HBIAS    = 24'h000040;
localparam [7:0] WW_W2       = 8'hdf;
localparam [9:0] WW_THRESH_PK = 10'h0e;
// hidden bias (decimal): [0, 1, 0, 0]
// output weights: [-1, -1, 1, -1]   threshold: 14
