// Auto-generated by train/train_sheila.py -- do not edit.
// sheila, H=4 WL=1, AUC 95.3%, nphase=2 shift=1 centre=7 nframe=8
// hidden template 135/192 non-zero (70%); zeros drop out of the adder tree.
localparam [383:0] WW_ROW      = 384'hd5c153d401311f11fc1ff1f3d57d43dfc0ffcffc74c14504ff5d1055715317c13453757f1505554507c13d3313f4df11;
localparam [23:0] WW_HBIAS    = 24'hf02000;
localparam [7:0] WW_W2       = 8'hfd;
localparam [9:0] WW_THRESH_PK = 10'h0e;
// hidden bias (decimal): [0, 0, 2, -4]
// output weights: [1, -1, -1, -1]   threshold: 14
