// Auto-generated by train/train_sheila.py -- do not edit.
// sheila, H=4 ternary, AUC 89.1%, nphase=2 shift=1 centre=6
// hidden template 237/320 non-zero (74%); zeros drop out of the adder tree.
localparam [639:0] WW_ROW      = 640'h1f00f0304d3f1fccf04cd5055157541405054d5fd4f1050c0f07d775c1754d535715c5354d5f57d54c5fd7c40704c571515714f5fd7c5f13c7f5cd3f51d347d1357d5f57d5f5f17d5f5715c0c4f53d7c;
localparam [23:0] WW_HBIAS    = 24'h101001;
localparam [7:0] WW_W2       = 8'hdd;
localparam [9:0] WW_THRESH_PK = 10'h0d;
// hidden bias (decimal): [1, 0, 1, 4]
// output weights: [1, -1, 1, -1]   threshold: 13
